// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMhffmV0ileLrGotRMDem7Ho1ycu9kZjQ',
    appId: '1:858277648871:web:60fa966940099d79144542',
    messagingSenderId: '858277648871',
    projectId: 'news-app-65f82',
    authDomain: 'news-app-65f82.firebaseapp.com',
    storageBucket: 'news-app-65f82.appspot.com',
    measurementId: 'G-C9LVL1664W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDe4Pqbu26f5YuoiCdAfbbP6uL-Dlsw7Q',
    appId: '1:858277648871:android:b98c5c5b86b347d2144542',
    messagingSenderId: '858277648871',
    projectId: 'news-app-65f82',
    storageBucket: 'news-app-65f82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG314JWEsnix0zp5Oyh8kf4VKee0KIph4',
    appId: '1:858277648871:ios:629a2943eb18e791144542',
    messagingSenderId: '858277648871',
    projectId: 'news-app-65f82',
    storageBucket: 'news-app-65f82.appspot.com',
    iosClientId: '858277648871-g6s8k3vlmcgvsngahu3r8ir2d2fb8m5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );
}
